import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-services',
  templateUrl: './services.component.html',
  styleUrls: ['./services.component.css']
})
export class ServicesComponent implements OnInit {

  constructor() { }

  data = [
    {heading:"Data Analysis",content:"Data Analytics initiatives can help businesses increase revenues, improve operational efficiency, optimize marketing campaigns & customer service efforts, respond more quickly to emerging market trends and gain a competitive edge over rivals. We can help. We support businesses in achieving fact-based decision-making by converting their historical and real-time, traditional and big data into actionable insights. Our services are tailored to make the raw data and the environment ready, as well as strengthen the business with advanced analytics capabilities.",img:"/assets/images/45.-Business-Analysis.svg",flipped:true},
    {heading:"ML and AI",content:"We make it easy for businesses to get clear about true potential from Artificial Intelligence and Machine Learning (ML). We help undertaking to make, take up, put to use and competent AI & ML solutions that provide better business outcomes. Our AI & ML cover powers businesses with intelligent features that eliminates human errors and increase performance by automating business activities.",img:"/assets/images/144.-Artificial-Intelligence.svg",flipped:false},
    {heading:"Web Development",content:"We offer custom web development services for front-end and back-end, including web application development. We focus on crafting visually engaging, and mobile responsive design. Not only do we build beautiful and functional websites/web-apps, we build them in a way that is maintainable and scalable.",img:"/assets/images/undraw_Web_developer_re_h7ie.svg",flipped:true},
    {heading:"Android App Development",content:"Android is one of the fastest growing operating systems for mobile application development. With a simple, versatile, flexible and user-friendly attributes, it has become everyone's favourite and liked operating system. Are you ready to make an Android application for your business but confused whether you should make an Android application or not? If you are looking for an Android application development company in India to get your application developed, you are at the right place! Being the world's most widely used mobile operating system with a various range of versions, Android development needs expert knowledge, experienced group that can balance the complex part of the general living conditions with the latest advances & high degrees in which event is probable of current-day mobile users. Our Android application development services help you make impactful things mobile applications for Android using best native & across-systems language. Our expert group has the brought up to the current state knowledge of the latest Android release invents and profitable Android applications. We make certain to give you high-quality Android applications to undergo growth of your business and make your customers happy, making ready you a good return of investment! You can be dependent on our experience and expert knowledge. Our Android application development services cover up-to-date integrated, seamless applications that are incredibly operative and combine compelling features that suits your business needs.",img:"/assets/images/undraw_android_jr64 (1).svg",flipped:false},
    {heading:"IOT",content:"Today, Internet of Things has gone from being just another concept to a brilliantly woven digital revolution that has impacted our daily lives. This advanced technology connects people, machines, processes, and systems onto one technology-enabled network. A number of enterprises and organizations are ready to unleash the potential of this powerful technology that will redefine the way we interact with other humans, machines, and devices. Here, we build apt IoT solutions that are dependent on the nature of need, and the extensiveness of the enterprise. The Internet-of-Things (IoT) is taking over everything. Increase audience size & decrease spend by deploying IoT features into your business.",img:"/assets/images/undraw_circuit_board_4c4d.svg",flipped:true},
    {heading:"RPA",content:"Business process automation must be in the hands of your frontline. Only we combine consumer-like usability with enterprise-class reliability, and security for RPA that empowers your workforce to automate on their own, in real time.",img:"/assets/images/undraw_robotics_kep0.svg",flipped:false},
    {heading:"Digitel Marketing",content:"Not sure how experienced online marketing agencies like SeaBorn Technologies can help your business? We provide free consultation, during which we will do a quick audit of various aspects of your online presence and let you know how internet marketing can help you boost your business. We understand that every business is unique. That’s why our affordable web development and SEO solutions are customized and specific to your business needs. We spare no resources to ensure your website is beautiful and optimized precisely to Google’s known variables. To effectively promote your brand on the Internet, we will spend a decent amount of time understanding your business and your market, and then create the most apt strategy to turn your business goals into reality. Whether you want to target an international audience or a local market, we will match the strategy accordingly. Let us help you plan out a customized digital strategy to conquer and lay siege to your enemies (or just take traffic away from them)!",img:"/assets/images/undraw_social_thinking_7ule.svg",flipped:true},
  ]

  ngOnInit(): void {
  }

}
